### ISSUE TITLE
a socket could not be bound

### ISSUE THREAD

**Issue by tugng** [encryptogroup/ABY#104]
Hi there,

I am a newbie in this field. I want to understand how MPC work. I successfully install ABY, but when I evaluate aes, this error occurs. any help? thanks.

./aes.exe -r 0

Error: a socket could not be bound
Listen failed
There was an error during establish connection, ending!

**Comment by lenerd** [comment]
Hi,

this can for example happen if there is already another program listening at the same port (or an older instance of the same program). You can use [netstat](https://linux.die.net/man/8/netstat) to check.

**Comment by lenerd** [comment]
I assume, this can be closed.

Also, you should check if that you use the latest version of ABY. There has not been a `aes.exe` anymore for some time. The corresponding example is now build as `aes_test`.
