### ISSUE TITLE
Parallelism question (and benchmarks)

### ISSUE THREAD

**Issue by ishaq** [encryptogroup/ABY#106]
I thought I had figured this out in #90 but...

### Q1
**Setting 1a:** 1 MUL operation. Arithmetic Sharing, 10Gbps LAN.
Result: 1000 executions result in average total time (online + setup) of about 6 milliseconds.

**Setting 1b:** 1000 MUL operations (all independent), Arithmetic Sharing, 10Gbps LAN.
Result: 1 execution result in average total time (online + setup) of 77 microseconds.

Obviously in the 1b setting, it is taking advantage of MULs being independent (low circuit depth). Is it doing any operations in parallel? (as in fig3 "Par" values of the ABY paper). If so, I gather there is no way to control this parallelism, right?

### Q2
**Setting 2a:** 1 MUL operation, Yao Sharing, 10Gbps LAN.
Result: 1000 executions result in average total time (online + setup) of about 3 milliseconds.

**Setting 2b:** 1000 MUL operations (all independent), Yao Sharing, 10Gbps LAN.
Result: 1 execution results in average total time (online + setup) of about 1.3 milliseconds. 

comparing setting 2a and 2b, I understand the relatively low improvement (Yao being communication intensive despite constant round). What I don't understand is why the results of **1b** are so much better than **2b**. 

PS: create a forum for questions may be? I feel bad for posting questions into issues.

**Comment by Aqua-Dream** [comment]
Hi, have you got the answer of Q1? Does ABY evaluate low depth circuit using multi-threads to reduce the computation time?
