### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by lumip** [encryptogroup/ABY#113]
I have been running into problems when trying to build ABY with the most recent commits. In particular, the file `src/abycore/aby/abyparty.cpp` fails to compile with the following error
```ABY/src/abycore/aby/abyparty.cpp: In member function ‘void ABYParty::ConnectAndBaseOTs()’:
ABY/src/abycore/aby/abyparty.cpp:121:46: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StartRecording("Starting NP OT", P_BASE_OT, m_vSockets);
                                              ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:123:47: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StopRecording("Time for NP OT: ", P_BASE_OT, m_vSockets);
                                               ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp: In member function ‘void ABYParty::ExecCircuit()’:
/ABY/src/abycore/aby/abyparty.cpp:191:48: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StartRecording("Starting execution", P_TOTAL, m_vSockets);
                                                ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:194:52: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StartRecording("Starting setup phase: ", P_SETUP, m_vSockets);
                                                    ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:205:52: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StartRecording("Starting OT Extension", P_OT_EXT, m_vSockets);
                                                    ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:207:59: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StopRecording("Time for OT Extension phase: ", P_OT_EXT, m_vSockets);
                                                           ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:235:51: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StopRecording("Time for setup phase: ", P_SETUP, m_vSockets);
                                                   ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:243:55: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
   StartRecording("Starting online phase: ", P_ONLINE, m_vSockets);
                                                       ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:245:54: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
   StopRecording("Time for online phase: ", P_ONLINE, m_vSockets);
                                                      ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp:249:41: error: could not convert ‘((ABYParty*)this)->ABYParty::m_vSockets’ from ‘vector<std::unique_ptr<CSocket>>’ to ‘vector<CSocket*>’
  StopRecording("Total Time: ", P_TOTAL, m_vSockets);
                                         ^~~~~~~~~~
/ABY/src/abycore/aby/abyparty.cpp: In member function ‘BOOL ABYParty::ABYPartyConnect()’:
/ABY/src/abycore/aby/abyparty.cpp:568:38: error: invalid initialization of reference of type ‘std::vector<CSocket*>&’ from expression of type ‘std::vector<std::unique_ptr<CSocket> >’
  return Connect(m_cAddress, m_nPort, m_vSockets, static_cast<uint32_t>(m_eRole));
```
I don't know about similar issues in other files as the compilation process stops there for me.
I'm currently running debian with gcc 6.3.0 so I also fetched and compiled gcc 8.2.0 and had the same issue occuring with that. This happens in both Debug and Release builds. Find the `cmake` output for the configuration that produced the above compilation output below:
``` -- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /gcc-8.2.0/bin/g++
-- Check for working CXX compiler: /gcc-8.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ENCRYPTO_utils
-- Found OTExtension
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.62.0
-- Configuring done
-- Generating done
-- Build files have been written to: /ABY/build-debug
```

I'm confused that this issue does not seem to be occuring in the travis test run.. maybe I'm missing something, could you maybe shed some light on this?

**Comment by dd23** [comment]
Unfortunately I cannot reproduce the issue.

Maybe you can answer the following points so we can try to narrow down what's going on:

Are you running cmake and make as described in the README?

Are all submodules updated to the newest revision? We recently changed some things in the ENCRYPTO_utils, which might be related.

Did you set the benchmarking Macros in `src/ABY_utils/ABYconstants.h:33-35` to 0 or 1?

**Edit:** While this is probably not directly related: Please also make sure to use a recent version of boost, as specified in the README. You need at least version 1.66 or newer.

**Comment by lumip** [comment]
I'm now finished going through your lists of questions:

- I ran `BOOSTROOT=$HOME/boost-1-67/ CC=$HOME/gcc-8.2.0/bin/gcc CXX=$HOME/gcc-8.2.0/bin/g++ cmake -DCMAKE_BUILD_TYPE=Debug ..` and `make` (used to do so without the BOOSTROOT until you mentioned that I needed >1.66)
- I tried updating the submodules via `git submodule update` (which did nothing) and manually checking out the latest commit in `master` of the submodules (which made some changes but did not resolve the issue)
- The `src/abycore/ABY_utils/ABYconstants.h` I left untouched (i.e., as checked out) meaning that all benchmarking macros are 0 as far as I can tell
- I got myself boost-1-67 to build against but that still did not resolve the issue

I must admit that I didn't really expect that anything of this would help as the problem at hand seems to be that an implicit conversion of an `std::vector<std::unique_ptr<CSocket>>` into `std::vector<CSocket*>`, i.e., cast from smart pointer into raw pointer must be available and as far as I know such an implicit conversion does not exist. I'm mostly puzzled that this problem does not occur on the travis CI..

**Comment by lenerd** [comment]
Hi,
this looks like the versions of ABY and ENCRYPTO_utils are somewhat out of sync:

Since the recent changes, the current (2fc858a8dc0dc43b5afee527a3c7b4e8c7552d16) ABYParty uses an `std::vector<std::unique_ptr<CSocket>>` for the sockets

https://github.com/encryptogroup/ABY/blob/2fc858a8dc0dc43b5afee527a3c7b4e8c7552d16/src/abycore/aby/abyparty.h#L104

The current versions (encryptogroup/ENCRYPTO_utils@889708f8771f32cb31dd6083c18b3921156e21d4) of `StartRecording` and `StopRecording` in ENCRYPTO_utils [also take a const reference to an `std::vector<std::unique_ptr<CSocket>>`](https://github.com/encryptogroup/ENCRYPTO_utils/blob/889708f8771f32cb31dd6083c18b3921156e21d4/src/ENCRYPTO_utils/timer.h#L78-L79).

Could you check, which version (-> commit ids) of the ABY repository and the extern/ENCRYPTO_utils submodule you have checked out?

**Comment by lumip** [comment]
Alright, I found the problem.

I did doublecheck the version of the submodules and not find an issue there. However.. I still had an older version of ABY and dependencies lingering around in the installation path (`/usr/local`) and cmake satisfied all ABY dependencies from there.. After removing those artifacts it now builds with the up-to-date version and compilation works just fine.

Thanks for the advice and the patience :) The issue has been resolved. I'll leave it open for a bit in case there's something left you'd want to add to this. If not, you may just close it
