### ISSUE TITLE
sample programs are not compiled

### ISSUE THREAD

**Issue by uishi** [encryptogroup/ABY#115]
Hello. I  found some compilation issue. (I'm sorry if this is a minor issue,  but I want to make it.)
I believe that this is not due to my use of g++-7.3.0 rather than g++-8.X.X. (I'm using g++-7.3.0 on ubuntu 18.04 LTS server.)

I can build the libaby.a from cmake and make commands (but with some warnings during cmake as follows).
```
-- Found ENCRYPTO_utils
-- Found OTExtension
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.68.0
-- Configuring done
CMake Error at src/abycore/CMakeLists.txt:1 (add_library):
  Target "aby" links to target "Boost::system" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at src/abycore/CMakeLists.txt:1 (add_library):
  Target "aby" links to target "Boost::thread" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
... // similar warning come
```

However, when I tried to build executable files the followings happen.
I used cmake with -DABY_BUILD_EXE=On.

```$ make
[ 25%] Built target aby
[ 26%] Linking CXX executable ../../bin/abytest
/usr/bin/ld: cannot find -lBoost::system
/usr/bin/ld: cannot find -lBoost::thread
collect2: error: ld returned 1 exit status
src/test/CMakeFiles/abytest.dir/build.make:284: recipe for target 'bin/abytest' failed
make[2]: *** [bin/abytest] Error 1
CMakeFiles/Makefile2:140: recipe for target 'src/test/CMakeFiles/abytest.dir/all' failed
make[1]: *** [src/test/CMakeFiles/abytest.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
Thank you.

**Comment by lenerd** [comment]
Hi,
so your CMake is not able to find the Boost components. Since you are on Ubuntu 18.04, I assume you have installed a custom version of Boost (not from the repositories). Do you still use the default CMake v3.10.2?
It looks like the FindBoost module, which is distributed with CMake, has to be adjusted for new Boost releases. According to [this](https://stackoverflow.com/a/42124857), you need at least CMake v3.13 for Boost 1.68.
Could you try again with a newer CMake version ([e.g. available here](https://cmake.org/download/))?

**Comment by uishi** [comment]
Exactly! I was using CMake v3.10.2 on my ubuntu 18.04.
After upgrading it to v13.3.2 for boost 1.68, the executable files were compiled successfully.
Thank you for your kind help.

**Comment by lenerd** [comment]
I am glad I could help you.
