### ISSUE TITLE
I have more gates then available

### ISSUE THREAD

**Issue by williamclot** [encryptogroup/ABY#117]
I'm getting the following error:
I have more gates then available: 

Any idea on how to delete this error?

Thanks

**Comment by lumip** [comment]
You can specify the maximum number of gates when creating the `ABYParty` object. Try increasing the default value to whatever you need (but be aware that this will likely increase memory consumption and time spent during precomputation)

**Comment by dd23** [comment]
It is not necessary to specify the number of gates manually anymore. Memory will scale dynamically until RAM is full. This was implemented a while ago in https://github.com/encryptogroup/ABY/pull/119.

**Comment by ZZIQIN** [comment]
> It is not necessary to specify the number of gates manually anymore. Memory will scale dynamically until RAM is full. This was implemented a while ago in #119.

will it allocate new memory after using party->Reset() and build new circult? the program seems to fill out the memory,i don't know whether memory leakage. i delete all share* returned by Put**Gate
