### ISSUE TITLE
Segfault when using the PSI example with YAO sharing

### ISSUE THREAD

**Issue by MartKro** [encryptogroup/ABY#122]
The example ./psi_phasing_test -r 1 -n 1 -b 32 -g 1 (YAO sharing) produces a segmentation fault when the framework is compiled in release mode. The segmentation fault does not occur when the framework is built in debug mode.

compiler: gcc (GCC) 8.2.1 20181127
debugger: GNU gdb (GDB) 8.2.1
cmake version 3.13.4

**Comment by MartKro** [comment]
It seems the issue is related to the used thread scheduling tools since the join method seems to produce the segmentation fault. The problem might be related to the missing refencence of the status, instead a NULL pointer is given, but further testing is needed.

When using the build of #123 the example does work. Further testing is needed before closing this issue though.

**Comment by lenerd** [comment]
Hi,

I think the reason of the crashes are the missing return statements of `gen_entries` and `gen_cuckoo_entries`. GCC and Clang already warned:
```
/home/lennart/uni/Encrypto/ABY/ABY/src/examples/psi_phasing/common/hashing/simple_hashing.cpp: In function ‘void* gen_entries(void*)’:
/home/lennart/uni/Encrypto/ABY/ABY/src/examples/psi_phasing/common/hashing/simple_hashing.cpp:126:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
```
```
/path/to/ABY/src/examples/psi_phasing/common/hashing/simple_hashing.cpp:126:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
```

Also, when compiled (even in Debug mode) with Clang, the program crashes with a SIGILL, which is often a good indicator for such problems:
```
Core was generated by `./bin/psi_phasing_test -r 0 -n 1 -b 32 -g 1'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000055d4781547d7 in gen_entries (ctx_tmp=0x55d4795b6860) at /path/to/ABY/src/examples/psi_phasing/common/hashing/simple_hashing.cpp:124
124		free(address);
```

A `return nullptr;` at the end of the functions should be sufficient to fix this.
