### ISSUE TITLE
PutSIMDCONSGate returns share with wrong value when nvals>447

### ISSUE THREAD

**Issue by ramym1** [encryptogroup/ABY#124]
Hi, I tried to create an SIMDShare consisting of 512 values equal to 1, but the returned share which contains zeroes at indexes 448-511.
Here is the code I wrote:

`	e_role role;
	uint32_t bitlen = 32, secparam = 128, nthreads = 1, vec_length = 128, p = 97;
	uint16_t port = 7766;
	std::string address = "127.0.0.1";
	e_mt_gen_alg mt_alg = MT_OT;
	e_sharing sharing = S_BOOL;

	seclvl sec_lvl = get_sec_lvl(secparam);

	std::cout
	    << "Enter role (enter 0 for SERVER and 1 for CLIENT)"
		<< std::endl;

	uint32_t int_role;
	std::cin >> int_role;
	role = static_cast<e_role>(int_role);

	ABYParty* party = new ABYParty(role, address, port, sec_lvl, bitlen, nthreads,
			mt_alg);

	// Get to know all the sharing types available in the program
	std::vector<Sharing*>& sharings = party->GetSharings();

	// Create the circuit object on the basis of the sharing type being inputed
	Circuit* circuit =
			(Circuit*) sharings[sharing]->GetCircuitBuildRoutine();

	uint32_t vec[512];
	for(int i=0; i< 512; i++) vec[i] = 1;
	share* vec_share = circuit->PutSIMDCONSGate(512, vec, 32);
	circuit->PutPrintValueGate(vec_share, "vec:\n");
	party->ExecCircuit();`

and in the output I get: [448]: 0; [449]: 0; [450]: 0; [451]: 0; [452]: 0; [453]: 0; [454]: 0; [455]: 0; [456]: 0; [457]: 0; [458]: 0; [459]: 0; [460]: 0; [461]: 0; [462]: 0; [463]: 0; [464]: 0; [465]: 0; [466]: 0; [467]: 0; [468]: 0; [469]: 0; [470]: 0; [471]: 0; [472]: 0; [473]: 0; [474]: 0; [475]: 0; [476]: 0; [477]: 0; [478]: 0; [479]: 0; [480]: 0; [481]: 0; [482]: 0; [483]: 0; [484]: 0; [485]: 0; [486]: 0; [487]: 0; [488]: 0; [489]: 0; [490]: 0; [491]: 0; [492]: 0; [493]: 0; [494]: 0; [495]: 0; [496]: 0; [497]: 0; [498]: 0; [499]: 0; [500]: 0; [501]: 0; [502]: 0; [503]: 0; [504]: 0; [505]: 0; [506]: 0; [507]: 0; [508]: 0; [509]: 0; [510]: 0; [511]: 0;

**Comment by MartKro** [comment]
I can confirm this bug. I'll be looking into it. I'll be looking into it.

**Comment by MartKro** [comment]
Pull request #127 should fix the issue.
