### ISSUE TITLE
Nothing happens when i run "./aes_test -r 1 -n 2"

### ISSUE THREAD

**Issue by yangningning** [encryptogroup/ABY#136]
Nothing happens when I execute "./aes_test -r 1-n 5" and the program does not end,as if it were died there.  what's the matter with it?

**Comment by Oleksandr-Tkachenko** [comment]
Hi @yangningning, try to use 2 terminals and run "./aes_test -r 0 -n 5" in the first terminal and "./aes_test -r 1 -n 5" in the second terminal.

**Comment by yangningning** [comment]
Thank you very much.
