### ISSUE TITLE
The communication costs are counted in the wrong phase

### ISSUE THREAD

**Issue by MartKro** [encryptogroup/ABY#139]
As I was trying to evaluate the communication costs of some tests at the YAO sharing method, I've encountered some odds. As it turns out they are counted into the wrong phase depending on how fast the main thread executes. For example for the abyfloat_test:

Server:
Total Sent / Rcv        649905  bytes / 4234 bytes
BaseOTs Sent / Rcv      49956  bytes / 49956 bytes
Setup Sent / Rcv        **18  bytes** / 4130 bytes
OTExtension Sent / Rcv  0  bytes / 4130 bytes
Garbling Sent / Rcv     **18  bytes** / 0 bytes
Online Sent / Rcv       **649887  bytes** / 104 bytes

Client:
Total Sent / Rcv        4243  bytes / 649914 bytes
BaseOTs Sent / Rcv      49947  bytes / 49956 bytes
Setup Sent / Rcv        4139  bytes / 641704 bytes
OTExtension Sent / Rcv  4130  bytes / 9 bytes
Garbling Sent / Rcv     0  bytes / 641695 bytes
Online Sent / Rcv       104  bytes / 8210 bytes

When I've slowed down the main thread (I've enabled yaoclientdebug/yaoserverdebug on the yaoclientsharing/yaoserversharing which caused the main thread to slow down due to the large outputs into the console) I've got the following results:

Server:
Total Sent / Rcv        649914  bytes / 4234 bytes
BaseOTs Sent / Rcv      49947  bytes / 49956 bytes
Setup Sent / Rcv        **637096  bytes** / 4130 bytes
OTExtension Sent / Rcv  0  bytes / 0 bytes
Garbling Sent / Rcv     **637087  bytes** / 0 bytes
Online Sent / Rcv       **12818  bytes** / 104 bytes

Client:
Total Sent / Rcv        4234  bytes / 649914 bytes
BaseOTs Sent / Rcv      49956  bytes / 49956 bytes
Setup Sent / Rcv        4130  bytes / 641704 bytes
OTExtension Sent / Rcv  4130  bytes / 9 bytes
Garbling Sent / Rcv     0  bytes / 637078 bytes
Online Sent / Rcv       104  bytes / 8210 bytes

To get those results I've also replaced the StartWatch("Starting Circuit Garbling", P_GARBLE);/StopWatch("Time for Circuit garbling: ", P_GARBLE); into StartRecording("Starting Circuit Garbling", P_GARBLE, m_vSockets);/StopRecording("Time for Circuit garbling: ", P_GARBLE, m_vSockets);

Therefore the communication costs (and therefore the timing costs probably as well) are incorrect evaluated.

I'll be looking into it further.

**Comment by dd23** [comment]
This should be fixed by  #140 so I guess we can close this issue.
