### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by prvsousa** [encryptogroup/ABY#14]
What type of authentication ABY has? 

You already implement the Extension to Malicious Adversaries?

**Comment by dd23** [comment]
If you're referring to the  parties' communication: This happens via plain sockets without any form of encryption. To use ABY in an open network one would need to add something like TLS for transport encryption or tunnel communication through a VPN.

ABY is currently only secure against semi-honest (passive) adversaries. An extension to malicious adversaries is not planned for the near future, but might be added at some point.
