### ISSUE TITLE
errors in make

### ISSUE THREAD

**Issue by Ye-D** [encryptogroup/ABY#141]
when I make in the build dir,I found the error as follows:
` error: ‘class channel’ has no member named ‘blocking_send’; did you mean ‘blocking_receive’?
   m_tPartyChan->blocking_send(m_vThreads[id]->GetEvent(), snd_buf_total, snd_buf_size_total);
                 ^~~~~~~~~~~~~
                 blocking_receive
`
and I found that there is no blocking_send in channel.
It seems that the Encrypto_utils has some bug.
Thank you very much.

**Comment by dd23** [comment]
Please make sure that the `ENCRYPTO_utils` submodule is up to date. `blocking_send()` was introduced [recently](https://github.com/encryptogroup/ENCRYPTO_utils/commit/0c50ffdfceae61ff7faad9ce3a8984fad1da6f56) and should be included in ABY.
You can do that with `git submodule update --init` for example.

**Comment by Ye-D** [comment]
Thank you very much,I have solved the problem.
