### ISSUE TITLE
Chameleon release?

### ISSUE THREAD

**Issue by ellio0ott** [encryptogroup/ABY#146]
I was wondering whether a public implementation of Chameleon was on the way or already available. From the paper it seems to be a quite powerful tool for MPC.

**Comment by cwb38** [comment]
Unfortunately not. The Chameleon version of ABY benchmarked in the paper is not in a shape that we would like to make publicly available and over the past two years became incompatible to the upstream version of ABY. However, we are still looking for students interested in re-implementing Chameleon and would also welcome community efforts.
