### ISSUE TITLE
cmake didn't find miracl

### ISSUE THREAD

**Issue by ZZIQIN** [encryptogroup/ABY#151]
I build the aby according the readme . But when i  try to build  own ABY Application ,cmake report the this error use find_package(ABY)
![Snipaste_2019-10-11_21-38-21](https://user-images.githubusercontent.com/16277522/66655959-9cefd880-ec6f-11e9-8e76-d9c418433e3a.png)

**Comment by lenerd** [comment]
Hi,
some time ago we replaced MIRACL as dependency with the RELIC library. I suggest you get the latest changes from the master branch and run CMake again in a clean build directory.

**Comment by ZZIQIN** [comment]
> Hi,
> some time ago we replaced MIRACL as dependency with the RELIC library. I suggest you get the latest changes from the master branch and run CMake again in a clean build directory.

But I've compiled it with the latest version.
![1570806190(1)](https://user-images.githubusercontent.com/16277522/66662438-6750ec80-ec7b-11e9-8ceb-8f8d3e65dc45.jpg)

**Comment by lenerd** [comment]
I just noticed that MIRACL is still referenced in some files. Could you remove the following line and check again?
https://github.com/encryptogroup/ABY/blob/6300c7975ea44e3bbb8644268c29b3e03c0a1f89/cmake/ABYConfig.cmake.in#L9

**Comment by ZZIQIN** [comment]
> I just noticed that MIRACL is still referenced in some files. Could you remove the following line and check again?
> https://github.com/encryptogroup/ABY/blob/6300c7975ea44e3bbb8644268c29b3e03c0a1f89/cmake/ABYConfig.cmake.in#L9


After the change, it becomes Can't find RELIC::relic. 
![1570810699(1)](https://user-images.githubusercontent.com/16277522/66667572-e64b2280-ec85-11e9-9ada-02948fa31e92.png)

**Comment by ZZIQIN** [comment]
i change the relic_config.cmake,it work.
![1570811694(1)](https://user-images.githubusercontent.com/16277522/66668632-43e06e80-ec88-11e9-8164-3a47aefb1b5f.png)

**Comment by lenerd** [comment]
Maybe open an issue at https://github.com/relic-toolkit/relic.
I cannot reproduce the issue on my system
