### ISSUE TITLE
How does aby connect to HElib?

### ISSUE THREAD

**Issue by WangLuyao627** [encryptogroup/ABY#155]

**Comment by dd23** [comment]
So far there is no connection between HElib and ABY. 
There are only some implementations of additively homomorphic encryption schemes (DJN/DGK) in ENCRYPTO_utils, if that helps: https://github.com/encryptogroup/ENCRYPTO_utils/tree/master/src/ENCRYPTO_utils/crypto

**Comment by WangLuyao627** [comment]
Thank you for your reply!
When I try to connect ABY and HElib,&nbsp;The following error occurred:

Would you know how to solve it?

Looking forward to your reply
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel D."<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上6:17
收件人:&nbsp;"encryptogroup/ABY"<ABY@noreply.github.com&gt;;
抄送:&nbsp;"王小瑶"<1746697445@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [encryptogroup/ABY] How does aby connect to HElib? (#155)




So far there is no connection between HElib and ABY.
 There are only some implementations of additively homomorphic encryption schemes (DJN/DGK) in ENCRYPTO_utils, if that helps: https://github.com/encryptogroup/ENCRYPTO_utils/tree/master/src/ENCRYPTO_utils/crypto

**Comment by dd23** [comment]
I can't see any error…

How are you trying to "connect" ABY and HElib!?

**Comment by WangLuyao627** [comment]
According to your request, I&nbsp;set the include path in my code and link my&nbsp;application to the libaby.a.
In HElib's Makefile, I add the following statement:
$(CC) $(CFLAGS) -o $@ $< fhe.a $(LDLIBS) -L. -laby -lencrypto_utils -lotextension -lrelic_s -lssl -lcrypto


But there will be a lot of undefined references.
boolsharing.cpp:(.text+0x21a5)：对‘std::filesystem::__cxx11::path::_M_split_cmpts()’未定义的引用
boolsharing.cpp:(.text+0x21ad)：对‘std::filesystem::status(std::filesystem::__cxx11::path const&amp;)’未定义的引用



ABY requires C++17, but ntl in HElib requires C++11, I think it might have some impact. Would you know it and what should I do?


Looking forward to your reply！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel D."<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 晚上11:17
收件人:&nbsp;"encryptogroup/ABY"<ABY@noreply.github.com&gt;;
抄送:&nbsp;"王小瑶"<1746697445@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [encryptogroup/ABY] How does aby connect to HElib? (#155)




I can't see any error…
 
How are you trying to "connect" ABY and HElib!?
