### ISSUE TITLE
psi_scs crashes when element number is bigger than 2

### ISSUE THREAD

**Issue by ShirleyYangyx** [encryptogroup/ABY#161]

**Comment by Mobiacikaka** [comment]
same here

**Comment by Mobiacikaka** [comment]
I figure it out. The element number must be the power of 2.

**Comment by zhou-pz** [comment]
Why the psi-scs still crashes when I try 2, 8 or 32  elements. Error message is following:

> psi_scs_test: ABY/src/examples/psi_scs/common/sort_compare_shuffle.cpp:150: int32_t test_psi_scs_circuit(e_role, const string&, uint16_t, seclvl, uint32_t, uint32_t, uint32_t, e_mt_gen_alg, uint32_t, bool): Assertion `circ_inter_ctr == ver_inter_ctr' failed.
> Aborted (core dumped)

**Comment by zhou-pz** [comment]
<table><tr><td bgcolor=gray> ss </td></tr></table>
