### ISSUE TITLE
Remote connection refused

### ISSUE THREAD

**Issue by lovingmage** [encryptogroup/ABY#168]
Hi,

When I try to test the millionaire example locally using 127.0.0.1, it works.

However, when I tried to test on two servers, it fails. And I found the server keeps refusing connections.

I tested using other programs such as netcat, the connection between these two machines are good. 

Just want to know how to solve such issue.

**Comment by dd23** [comment]
The millionaire problem example takes a few arguments that you can use for this. The following is how you would call the executables on the two machines. Role 1 (the client) just needs to specify the IP of the machine that role 0 (the server) runs on. The port is optional.

`./millionaire_prob_test -r 1 -a  <SERVER-IP> -p <PORT>`
`./millionaire_prob_test -r 0 -p <PORT>`

Have a look [here](https://github.com/encryptogroup/ABY/blob/public/src/examples/millionaire_prob/millionaire_prob_test.cpp) to see how this is handled in the example code.

If that does not work, maybe try a different port. ABY uses 7766 as a default, maybe that one is blocked on your network for some reason.

**Comment by Moriarty002** [comment]
Hi @dd23 ,
I met same problem when I used the AWS server(EC2)
I have checked that the IP-address is right , the connection is well (43.0 Mbits/sec) , the port(7766) is not blocked

I have execute command below , and all of them didn't work
1. 
EC2 : ./aes_test -r 0 -p 7766
local : ./aes_test -r 1 -a <addr> -p 7766
2.
EC2 : ./aes_test -r 0 -p 44444 7766
local : ./aes_test -r 1 -a <addr> -p 7766

both of above show 
```
Connect failed due to timeout!
There was an error during establish connection, ending! 
```

Is there some argument I miss?

**Comment by dd23** [comment]
FYI: There was a typo (an extra '44444') in the commands of my reply above, I have fixed it now.

You should also remove it from your 2. command line unless you want to use port 44444 (which both sides should do then).

Also, you need to specify the EC2 IP address after -a, otherwise the client does not know where to connect to.

**Comment by Moriarty002** [comment]
> FYI: There was a typo (an extra '44444') in the commands of my reply above, I have fixed it now.
> 
> You should also remove it from your 2. command line unless you want to use port 44444 (which both sides should do then).
> 
> Also, you need to specify the EC2 IP address after -a, otherwise the client does not know where to connect to.

It was I forgot to type when asking
I am sure that when I using , I had type address
