### ISSUE TITLE
[question] Can ABYParty be reused?

### ISSUE THREAD

**Issue by Mobiacikaka** [encryptogroup/ABY#170]
For example, in the millionaire's problem, how can I call function PutINGate and ExecCircuit several times without destroying the class ABYParty?

**Comment by dd23** [comment]
That is possible using `party->Reset()`.
See here for an example https://github.com/encryptogroup/ABY/blob/08baa853de76a9070cb8ed8d41e96569776e4773/src/examples/bench_operations/bench_operations.cpp#L449
