### ISSUE TITLE
Does the library implement the example modular exponentiation mentioned in paper

### ISSUE THREAD

**Issue by L-coder148** [encryptogroup/ABY#171]
hello, it seems that the library does not implement the example modular exponentiation mentioned in paper.
![image](https://user-images.githubusercontent.com/75669641/104303153-af0c9680-5504-11eb-8f66-a7ce95638be8.png)

**Comment by dd23** [comment]
That's correct.
Feel free to submit a pull request if you think we should include it in the repo. Thanks!
