### ISSUE TITLE
Two-party computing with unknown/hidden circuit

### ISSUE THREAD

**Issue by StickBrush** [encryptogroup/ABY#173]
Hello everyone! My issue is more of a question of whether something is or is not possible in ABY than an actual issue with the framework.

Imagine we have Alice and Bob. Alice wants to do some concrete computation (which can be something like the Millionaire's Problem) using some data of her own and some of Bob's data. Both Alice's and Bob's data is private and cannot be released in cleartext, so they use ABY to do this computation. Is it possible for Alice to do this without letting Bob know the underlying computation she's actually going to use? Can Alice just ask Bob for his money in encrypted form, receive the information in an unreadable format for her (an ABY share, preferably) and do some computation by herself with that information?

Thank you in advance for clearing this doubt!

**Comment by dd23** [comment]
Hi,
what you describe sounds very much like a technique called **Private Function Evaluation** in the literature, which can be achieved e.g. by using so-called universal circuits.
We have code for generating such universal circuits, which can be evaluated with the ABY framework here: https://github.com/encryptogroup/uc
Feel free to have a look at it and at the related papers, which you can find in the README in the UC repo.

The code for evaluating these circuits with ABY is located here: https://github.com/encryptogroup/ABY/tree/public/src/examples/uc_circuit
