### ISSUE TITLE
Can use get_clear_value() and its clear out before ExecCircuit() ?

### ISSUE THREAD

**Issue by YuXinFan** [encryptogroup/ABY#179]
I want to access the clear value of some shares and use the clear value to control the execution. 
Only add  PutOutGate() and get_clear_value() nothing happens. But it always gives me `Segmentation fault`  when I want to read the clear value. 

Doesn't ABY allow this action?

**Comment by Moriarty002** [comment]
![image](https://user-images.githubusercontent.com/43646155/133273518-7ad5cec1-c948-4434-b2ad-26f6494475f2.png)
Maybe miss ```Reset()``` ? I met similar problem before , and solve by this way .
