### ISSUE TITLE
abstract class without virtual destructor

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ABY#19]
The class [`Sharing`](https://github.com/encryptogroup/ABY/blob/990f30673082140ef00f33d53340d2089d2f5a00/src/abycore/sharing/sharing.h#L43) is an abstract base class, but its [destructor](https://github.com/encryptogroup/ABY/blob/990f30673082140ef00f33d53340d2089d2f5a00/src/abycore/sharing/sharing.h#L65-L67) is not declared virtual.

[see C++ FAQ](https://isocpp.org/wiki/faq/virtual-functions#virtual-dtors)

```
src/abycore/aby/abyparty.cpp:126:3: warning: delete called on 'Sharing' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete m_vSharings[S_BOOL];
                ^
src/abycore/aby/abyparty.cpp:128:3: warning: delete called on 'Sharing' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete m_vSharings[S_YAO];
                ^
src/abycore/aby/abyparty.cpp:130:3: warning: delete called on 'Sharing' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete m_vSharings[S_YAO_REV];
                ^
src/abycore/aby/abyparty.cpp:132:3: warning: delete called on 'Sharing' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete m_vSharings[S_ARITH];
```

**Comment by dd23** [comment]
Thanks for reporting.
This has been fixed with the most recent merge from master in f57e24669e445d2c19924dcd5069aa13f4a64da4
