### ISSUE TITLE
S_SPLUT

### ISSUE THREAD

**Issue by iconley** [encryptogroup/ABY#193]
Are there any reference books or papers for the S_SPLUT sharing?

**Comment by dd23** [comment]
Hi,
the idea behind this sharing is described in this paper:
"Pushing the Communication Barrier in Secure Computation using Lookup Tables"
Ghada Dessouky, Farinaz Koushanfar, Ahmad-Reza Sadeghi, Thomas Schneider, Shaza Zeitouni, and Michael Zohner 
NDSS'17
https://eprint.iacr.org/2018/486
