### ISSUE TITLE
How to use it as remote MPC for multi-side  usage?

### ISSUE THREAD

**Issue by JiangDonglai98** [encryptogroup/ABY#199]
For code right now found, it supports localhost(127.0.0.1:7766 as default socket connection) usage. How can I use it as remote MPC? For example, A party on one side PC has its own IP address and port and B party on the other side PC has its own IP address and port. I donot find any API settings for this situation. Should I rewrite the CSocket part in the extern pacakge like ENCRYPTO_utils and OTEExtension to acheive things like what I describe or there is an easy way to set some params to do it?

**Comment by dd23** [comment]
It is possible to use ABY without bigger modifications over networks.

Have a look at the Euclidean distance example: https://github.com/encryptogroup/ABY/blob/public/src/examples/euclidean_distance/euclidean_distance_test.cpp

There you can specify an IP address as cmd line parameter, which gets then passed on.

**Comment by JiangDonglai98** [comment]
Thanks a lot for your reply. May I have a nonsensical request? Since I am a newer to C++, I do not see an over network example in  Euclidean distance example code. Can you give a simple example of setting up  ABYParty for over  network settings or cmd line commands? Sorry for the inconvenience.

**Comment by JiangDonglai98** [comment]
I know the markdown example command line setting "./millionaire_prob_test -r 0 and ./millionaire_prob_test -r 1, each in a separate terminal" is to select the server and the client using '-r', but what about the ip address and port's leading symbol. Sorry for the stupid question.

**Comment by JiangDonglai98** [comment]
Oh, I got it in the parsing_ctx, thanks a lot.
