### ISSUE TITLE
PSI Examples won't compile

### ISSUE THREAD

**Issue by JavaJens** [encryptogroup/ABY#2]
I have a problem compiling the examples.
In psi_phasing.cpp the compiler complains:

```
common/phasing_circuit.o: In function `BooleanCircuit::PutINGate(unsigned int, unsigned int, unsigned int, e_role)':
phasing_circuit.cpp:(.text._ZN14BooleanCircuit9PutINGateEjjj6e_role[_ZN14BooleanCircuit9PutINGateEjjj6e_role]+0x1): undefined reference to `share* BooleanCircuit::InternalPutINGate<unsigned int>(unsigned int, unsigned int, unsigned int, e_role)'
```

A similar error occurs for the psi_scs example, all others compile just fine.
Any help is greatly appreciated!

**Comment by dd23** [comment]
Hi @JavaJens 
Sorry for this problem. 

We have recently changed the call to `PutINGate()` with one of the last commits and have obviously forgotten to update the PSI_Phasing example.

I will upload a new revision that fixes this issue very soon. If you don't want to wait until then, you can replace every occurence of  `PutINGate()` with  `PutSIMDINGate()`, which should do the trick.

**Comment by JavaJens** [comment]
Thanks for the super fast reply!
Replacing every occurrence didn't help, so I'll wait for your release.

**Comment by dd23** [comment]
Sorry for the confusion, but the replacement that I described earlier is actually not on github yet (but will be in the next couple of days).
However, on my machine the current revision here on github compiles just fine, including the PSI examples.

Have you tried running a `make cleanmore` in the root folder before you run `make`? Did you set up everything as described in the [Readme](https://github.com/encryptogroup/ABY/blob/public/README.md#requirements)?

Please let me know if you managed to fix the problem or if it persists. Thanks!

**Comment by JavaJens** [comment]
`make cleanmore` didn't help. However I was able to compile on a different machine, so this is a local issue.
Thanks for the fast help!
