### ISSUE TITLE
create_new_share declared static

### ISSUE THREAD

**Issue by lenerd** [encryptogroup/ABY#21]
In section _2.2.4 Share Creation_ of the developer guide the following functions are introduced:
```C++
static share* create_new_share(uint32_t size, Circuit* circ);
static share* create_new_share(vector<uint32_t> wireids, Circuit* circ);
```
They are defined in [src/abycore/circuit/circuit.cpp](https://github.com/encryptogroup/ABY/blob/5230443c0fe74d5ef35e410f8c9f96dd461c6c01/src/abycore/circuit/circuit.cpp#L365-L387) using the `static` keyword. Therefore the symbols are not exported and the function can only be used in the same translation unit. Using them in another file results in a linking error.

If these functions are meant to be part of the public API, I see no reason to declare them static. Otherwise they should neither be exposed by the headers nor advertised in the documentation.

My guess is someone moved them from class to namespace scope and forgot to remove the static modifier.

**Comment by dd23** [comment]
fixed in 343dc69c0b6c8c41c7fb5ae1f3b7b61b0d39ead1
thanks!
