### ISSUE TITLE
Socket recv error

### ISSUE THREAD

**Issue by akappy7** [encryptogroup/ABY#35]
Hi, I was testing party->reset( ) functionality and it seems that whenever that function is invoked, one of the terminals that runs the program is killed and the other terminal outputs "socket recv: unexpected shutdown by peer". 

The code I was testing included: 
  ```
 1. Loop thru some iterations:
      2. create a Circuit * ptr for a boolean circuit. 
      3. Put in values (via PutINGate)
      4. Put in operations (sub/mul) on create share objects
      5. party->ExecCircuit()
      6. extract values (via PutOUTGate)
      7. party->Reset()
```

Similar behavior is seen when I tested the example program "./bench_operations.exe". 

Are there system/environment preference that needs to be modified in order to avoid the sockets from closing unexpectedly?

**Comment by Oleksandr-Tkachenko** [comment]
Hi, could you please provide the code you have used?

**Comment by akappy7** [comment]
Hi, I used "bench_operations" example as is under src/examples/bench_operations/bench_operations.cpp, no modifications made. 

As far as my own code, the snippet that causes the problem is: (the rest of the code follows the same setup as millionaire problem example, let me know if you want the whole file)

```
    for(int i = 0; i < numIter; i++){
           circB = (BooleanCircuit*) sharings[S_BOOL]->GetCircuitBuildRoutine();
           share * a = circB->PutINGate(x[i], BITLEN, CLIENT);
           share * b = circB->PutINGate(x[i], BITLEN, SERVER);

           share * output = circB->PutADDGate(a, b);
           share * out = circB->PutOUTGate(output, ALL);

          party->ExecCircuit();

          solution[i] = out->get_clear_value<uint32_t>();

          party->Reset();     
     }
```

**Comment by akappy7** [comment]
The problem was caused by the number of gates that my personal system could handle (due to memory limitation). I solved the issue with reducing the max number of gates during the party initialization.
