### ISSUE TITLE
parent->context == S_YAO || S_YAO_REV

### ISSUE THREAD

**Issue by david-k** [encryptogroup/ABY#40]
Hi,

in src/abycore/sharing/yaoclientsharing.cpp:440 it says `else if(parent->context == S_YAO || S_YAO_REV)` but it should probably be `else if(parent->context == S_YAO || parent->context == S_YAO_REV)`.

Best,
David

**Comment by dd23** [comment]
That was indeed an oversight.
I have fixed this in 112fb855bd2be16dc548c9ef400340fefbd36cc5

Thanks for reporting this.
