### ISSUE TITLE
The link of Developer Guide is expired

### ISSUE THREAD

**Issue by shangqi-lai** [encryptogroup/ABY#47]
I was trying to download the developer guide from your website (https://www.encrypto.informatik.tu-darmstadt.de/fileadmin/user_upload/Group_ENCRYPTO/code/ABY/devguide.pdf), but it gives 404. Could you please fix the link?

Thank you.

**Comment by dd23** [comment]
I have fixed the URL in the README in e1cdb3392fb1c64418a7f9b871fff0216ac38351

The new URL for the developer guide is: https://www.informatik.tu-darmstadt.de/media/encrypto/encrypto_code/abydevguide.pdf
