### ISSUE TITLE
Running program between two computers

### ISSUE THREAD

**Issue by jpmcruz** [encryptogroup/ABY#52]
We tried running the millionaire_prob in two terminals in one virtual machine in the same computer, and it works okay.
Then, we tried running the millionaire_prob between two virtual machines in the same computer, and it works okay.
But, we cannot successfully run the millionaire_prob between two computers (comp 1 and comp 2) connected by LAN.

comp 1 has the following details:
IP Address - 192...001
Port - default

comp 2 has the following details:
IP Address - 192...002
Port - default

If we want to run the millionaires problem on these computers (comp 1 as server, comp 2 as client)
what should be the syntax on both computers?

When we type "./millionaire_prob.exe -r 0 -a 192...001" in a terminal in comp 1 and "./millionaire_prob.exe -r 1 -a 192...001" in a terminal in comp 2, both terminals do not return anything and run indefinitely. 

Any help would be appreciated.

**Comment by dd23** [comment]
I tried running millionaire_prob.exe on 2 separate machines in our network and the code worked just fine.

What you could check:
You need to make sure that communication through the port (default: 7766) is working.
Also, the IP-address that you specify with `-a` must be the one of the server (`-r 0`).

Does that help you?

**Comment by jpmcruz** [comment]
I will have a look at this, thank you!
