### ISSUE TITLE
PrintValueGate and AssertGate

### ISSUE THREAD

**Issue by jan-bruckner** [encryptogroup/ABY#6]
In the developer guide you mention `PutPrintValueGate` and `PutAssertGate`.
Since I cannot seem to find those in the current release, I'm assuming you have a more recent version, which is not yet released?
Are you planning to release those anytime soon?

Thanks for your great work 👍

**Comment by dd23** [comment]
Thanks for the hint. We will update to the new release that contains these new gates within the next few days.

**Comment by jan-bruckner** [comment]
Great to hear, looking forward to it :)
