### ISSUE TITLE
Segfault when PRINT_PERFORMANCE_STATS is defined

### ISSUE THREAD

**Issue by jan-bruckner** [encryptogroup/ABY#7]
When using `#define PRINT_PERFORMANCE_STATS` I get a segfault [here](https://github.com/encryptogroup/ABY/blob/public/src/abycore/aby/abyparty.cpp#L469) because `m_vSharings.size()` is 4 while `S_BOOL_NO_MT` is 5 [here](https://github.com/encryptogroup/ABY/blob/public/src/abycore/util/constants.h#L182).
Commenting out that one line for now. Just wanted to let you know.

**Comment by dd23** [comment]
Thanks a lot for finding and reporting this! I have commented out the line that you mentioned.
`S_BOOL_NO_MT` is currently under construction and will be added soon. We will also put back the performance stats for it, once it's ready.
