### ISSUE TITLE
make fails (openssl issues) with Ubuntu 16.04 and libssl-dev 1.0.2g

### ISSUE THREAD

**Issue by mayank0403** [encryptogroup/ABY#74]
With the current commit of the public branch, make fails with openssl errors on Ubuntu 16.04.
I checked the travis log of this repo and found that the openssl version that the travis CI uses is 1.0.1f (which is available for 14.04) which is not available for Ubuntu 16.04. The latest version of libssl-dev for Ubuntu 16.04 is 1.0.2g. 
This causes the make to crash.
I am attaching the make log on my machine running Ubuntu 16.04 with libssl-dev 1.0.2g. Errors are shown from line 12 to line 30 in the log.
[makelog.txt](https://github.com/encryptogroup/ABY/files/2266513/makelog.txt)

**Comment by lenerd** [comment]
Hi,

using my Ubuntu 16.04 VM (with `libssl-dev` version `1.0.2g-1ubuntu4.13`) I cannot reproduce this build error.

However, I noticed in your log file that the OpenSSL header are included from `/usr/local/include` (e.g. `/usr/local/include/openssl/bio.h`) instead of the standard location `/usr/include`. So you have probably installed another (older?) version of OpenSSL installed on your system at `/usr/local`.

The header from the `libssl-dev` package are all installed  to `/usr/include`. You can verify it with `dpkg -L libssl-dev`. To check whether another package owns a file, you can use `dpkg -S /path/to/file`.

**Comment by mayank0403** [comment]
Hey, I found that I had another version of openssl installed in /usr/local/include and when I removed it, the make proceeded upto a point where I face this issue with some methods from openssl/evp.h undefined.
I checked it all and I just have one version of openssl on my system now which is the same as the one you used above in the VM.
I am attaching the log file of make error. Please take a look.
[error_log.txt](https://github.com/encryptogroup/ABY/files/2267321/error_log.txt)

**Comment by lenerd** [comment]
Did you remove the complete OpenSSL installation, i.e., also the library files for `libcrypto` and `libssl` in `/usr/local/lib`? Maybe it tries to link against the old version, which does not have these symbols.

**Comment by mayank0403** [comment]
Yes, I removed everything. 
I just checked and both `libcrypto` and `libssl` are now only in /usr/lib.

**Comment by dd23** [comment]
It's a bit hard to debug this. In any case ENCRYPTO_utils (and thus ABY) should be able to handle both OpenSSL 1.0.x and 1.1.x (see [here](https://github.com/encryptogroup/ENCRYPTO_utils/blob/master/src/ENCRYPTO_utils/crypto/crypto.h#L40) and where `OPENSSL_OPAQUE_EVP_CIPHER_CTX` is used).

Maybe some very basic things: did you reboot your system after these library changes? Did you run a fresh build, e.g. by running `make clean` to make sure there are no old artifacts?

**Comment by mayank0403** [comment]
I really appreciate all the help and I will make sure that I give it one more shot. Will check again if all the library files of openssl are removed from /usr/local/lib and then reboot my system again.
I am sure that I am running make after make clean only.
Will report back if I find something.
Thanks.

**Comment by lenerd** [comment]
Just to make sure that there is no other installation left anywhere. Could you give us the output of:
```
$ ldconfig -XNv | grep -P '(^/|ssl|crypto)'
```

**Comment by mayank0403** [comment]
Here is the output of the `ldconfig` command.
[log.txt](https://github.com/encryptogroup/ABY/files/2269093/log.txt)

**Comment by mayank0403** [comment]
It works now. It turned out that the correct version of the openssl crypto library's `libcrypto.so` was not present in `/usr/lib` but in `/usr/lib/x86_64-linux-gnu`. I copied it from there to `/usr/local/lib` and that made it work.

Thank you very much.

**Comment by lenerd** [comment]
I assume this issue can be closed then.
