### ISSUE TITLE
How to interpret Benchmark Times

### ISSUE THREAD

**Issue by ishaq** [encryptogroup/ABY#90]
I'm probably being lazy by not checking it in the source code and asking question here but my rationale is that this topic is covered in the developer guide and therefore should be clarified for the end-users/general-public. If I didn't get an answer, I'll dig deeper and post my findings.

My output looks like this (relevant excerpt):

```
Timings: 
Total =		13.331 ms
Init =		376.002 ms
CircuitGen =	8.516 ms
Network =	7247.1 ms
BaseOTs =	492.589 ms
Setup =		8.102 ms
OTExtension =	2.839 ms
Garbling =	0.643 ms
Online =	5.225 ms
```

Question is, **why is Total time less than Init time?** How should we interpret the different times? If it helps, my program is a simple multiplication gate (Alice and Bob input a and b, result is a*b). it has only 4 gates. (two input gates, one multiplication gate and one reconstruction (OUT) gate). 

Also, I am executing it in Arithmetic Sharing, so Garbling time doesn't make much sense.

**Comment by dd23** [comment]
Hi,

this is briefly explained at the very end of the [Devguide](https://www.informatik.tu-darmstadt.de/media/encrypto/encrypto_code/abydevguide.pdf): "The total time is the time for the setup phase and the online phase combined."

Init Time is the time to allocate memory and "build" the circuit, which should also only happen once and is thus not counted into total time.

Garbling is <1ms in your example, which is fine, since it's basically just the routines checking for Yao gates, not finding any and exiting.

**Comment by ishaq** [comment]
Thanks @dd23 , what is setup time and base OT

**Comment by ishaq** [comment]
spoke too soon. SetupTime and BaseOT time is indeed covered in the dev guide. closing the ticket.

**Comment by ishaq** [comment]
So, how do I calculate the total time (to differentiate say, arithmetic circuit time from yao circuit time). Should I add Total + Garbling + CircuitGen?

**Comment by dd23** [comment]
If you have defined `BENCHONLINEPHASE` as `1` [here](https://github.com/encryptogroup/ABY/blob/public/src/abycore/ABY_utils/ABYconstants.h#L35), you will get detailed results for every sharing as output, as implemented [here](https://github.com/encryptogroup/ABY/blob/public/src/abycore/aby/abyparty.cpp#L431). 
Those numbers are only for the online phase and should add up to the number printed as "Online = " in the later benchmark numbers.

Garbling time should be already in the setup time and thus in the total time.

Does that help you?

**Comment by ishaq** [comment]
Yes, and no. :-) sorry, Now I completely understand what the different times are, but it doesn't solve what I am trying to solve. (feel free to ignore me if it sounds like I am trying to get you to do my work).

I am trying to come up with the time it takes to execute an instruction in ABY (the paper does not contain all the times I need, also since the paper is 4 years old, I thought it would be a good idea to recompile the table).

Now the problem is, MUL instruction (bitlen = 32) should be faster in Arithmetic repr than in Yao. in my case (I am averaging over 1000 executions of this simple MUL circuit), this is not necessarily the case. I am using the total time. From here, I am going to try two things:

1. Instead of taking the Total time, Take gate specific time from BENCHONLINEPHASE  + Setup Time. (I don't think it would make much difference though, the times are really close there too).
2. Instead of just one MUL, perform 1000 MUL gates and time them.

Currently I am doing 2 instead of 1 because I think it's more promising.

Thanks for all your help.

**Comment by dd23** [comment]
MUL in arithmetic sharing should be faster than in Yao in many cases. The limiting factor is the network, mostly in the sense that you need to do 1 round per data-dependent layer of MUL gates in arith. sharing, while you only do a constant number of rounds in Yao, independent of the circuit you are evaluating.
That means, if you're on a high-latency network and your circuit has a high multiplicative depth, Yao will probably be the faster option, unless your throughput is very small as well...

So depending on the network (we benchmarked on a local Gigabit LAN and used Amazon EC2 for a slower WAN connection) and if your MUL operations are sequential (data-dependent) or in parallel (independent inputs), Yao or Arith might be faster. This can also be seen in the ABY paper in Fig. 2 and Fig. 3, where we measured the setup and online phase separately.

In general averaging over many operations is a good idea, to remove a bit of the influence of weird network behavior on your running time measurements.

**Comment by ishaq** [comment]
yep, I agree. However, in my case I was testing it all on a local machine (two subprocesses) so it was inter-process communication. Must have been something weird because as soon as I started averaging over, say, 100 multiplications (no parallelism), the time for Arith. sharing has significantly reduced compared to Yao sharing.

Thanks Daniel. On a side note, please take a look at the PRs and merge them soon-ish. :-)
